import { MessageCircle, Pencil, RefreshCw, Send } from "lucide-react"

import { cn } from "@/lib/utils"
import { BRAND } from "@/core/constants/brand"
import { StatusPill } from "@/core/widgets/StatusPill"
import { PrimaryButton, SecondaryButton } from "@/core/widgets/Buttons"
import { Textarea } from "@/components/ui/textarea"

/**
 * The WhatsApp composer. Editable by default, with an explicit regenerate action
 * and a single send button that hands off to WhatsApp with the text prefilled.
 */
export function WhatsAppMessageCard({
  message,
  customerName,
  onChange,
  onRegenerate,
  onSend,
  sending,
  editing,
  onToggleEdit,
}: {
  message: string
  customerName: string
  onChange: (value: string) => void
  onRegenerate: () => void
  onSend: () => void
  sending?: boolean
  editing: boolean
  onToggleEdit: () => void
}) {
  return (
    <div className="rounded-3xl border border-border/70 bg-card p-5 shadow-card">
      <div className="mb-3 flex items-center justify-between gap-2">
        <StatusPill tone="purple" size="md" icon={<MessageCircle className="size-3.5" />}>
          {`AI generated by ${BRAND.employeeName}`}
        </StatusPill>
        <button
          type="button"
          onClick={onToggleEdit}
          className="text-caption inline-flex min-tap items-center gap-1.5 rounded-2xl px-3 font-bold text-blue"
        >
          <Pencil className="size-4" aria-hidden />
          {editing ? "Done" : "Edit"}
        </button>
      </div>

      <div
        className={cn(
          "relative rounded-[22px] rounded-tl-md border border-brand/15 bg-brand-soft p-4"
        )}
      >
        <span
          className="absolute -top-px -left-px size-3 rounded-full bg-card"
          aria-hidden
        />
        {editing ? (
          <Textarea
            value={message}
            onChange={(event) => onChange(event.target.value)}
            aria-label={`WhatsApp message to ${customerName}`}
            className="min-h-32 resize-none rounded-2xl border-brand/25 bg-card text-[15px] leading-relaxed"
          />
        ) : (
          <p className="text-[15px] leading-relaxed whitespace-pre-line text-ink">
            {message}
          </p>
        )}
      </div>

      <p className="text-caption mt-3 text-ink-soft">
        To {customerName} · sent from your business number
      </p>

      <div className="mt-4 flex flex-col gap-2.5">
        <PrimaryButton
          tone="brand"
          icon={<Send />}
          onClick={onSend}
          loading={sending}
        >
          Send on WhatsApp
        </PrimaryButton>
        <SecondaryButton icon={<RefreshCw className="text-purple" />} onClick={onRegenerate}>
          Regenerate
        </SecondaryButton>
      </div>
    </div>
  )
}
